export const SET_DATA_WORKSPACE = 'SET_DATA_WORKSPACE';
export const CREATE_LIST_DIRECT_MESSAGE = 'CREATE_LIST_DIRECT_MESSAGE';
export const CREATE_INITIAL_DIRECT_MESSAGE = 'CREATE_INITIAL_DIRECT_MESSAGE';
export const DELETE_DIRECT_MESSAGE = 'DELETE_DIRECT_MESSAGE';