export const SELECT_MEMBER = 'SELECT_MEMBER';
export const SET_INITIAL_LIST_CHANNEL = 'SET_INITIAL_LIST_CHANNEL';
export const CREATE_CHANNEL = 'CREATE_CHANNEL';
export const DELETE_CHANNEL = 'DELETE_CHANNEL';
export const SET_INFOR_CHANNEL = 'SET_INFOR_CHANNEL';
export const HIDE_CHAT_CONTENT = 'HIDE_CHAT_CONTENT';